import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
export default function Home() {
  const [sueldoBruto, setSueldoBruto] = useState('')
  const [sueldoNeto, setSueldoNeto] = useState(0)
  const [obraS, setObraS] = useState(0)
  const [pami, setPami] = useState(0)
  const [jubilacion, setJubilacion] = useState(0)
  function sueldo(e) {
    const amount = e.target.value
    setSueldoBruto(Number(amount))
    const obraSocial = amount * 0.03
    setObraS(obraSocial)
    const descuentoINSSJP = amount * 0.03
    setPami(descuentoINSSJP)
    const jubilacion = amount * 0.11
    setJubilacion(jubilacion)
    const discounts = obraSocial + descuentoINSSJP + jubilacion
    const finalAmount = amount - discounts

    setSueldoNeto(finalAmount)
    console.log(Math.ceil(finalAmount))
    
  }
  function reiniciar(e) {
    setSueldoBruto('')
    setObraS(0)
    setPami(0)
    setJubilacion(0)
    setSueldoNeto(0)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <label>Sueldo bruto
          <input type='number' onChange={sueldo} value={sueldoBruto}></input>
        </label>
        <h2>Descuentos</h2>
        <p>Obra social:${obraS}</p>
        <p>Pami:${pami}</p>
        <p>Jubilacion:${jubilacion}</p>
        <h2>Total</h2>
        <p className={styles.sueldoFinal}>Sueldo neto:<span className={styles.sueldoFinalNumber}>${sueldoNeto}</span></p>
        <button onClick={reiniciar}>REINICIAR</button>

      </main>

     
    </div>
  )
}
